### ISSUE TITLE
[PENAMBAHAN] [PERUBAHAN] Pembayaran dan Operasional

### ISSUE THREAD

**Issue by ctw28** [localhousecv/Pendataan-Pengeluaran-Uang-Android#9]
**OPERASIONAL SEWA ALAT DAN MOBIL**

- [x] OPERASIONAL SEWA ALAT dan MOBIL -> _cek apakah berfungsi kalau melapor tanggal yang sama muncul peringatan tidak boleh isi tanggal yang sama_
- [x] Selebihnya ada di File **HASIL KETEMUAN KLIEN** yang kemarin sa kirim

**PEMBAYARAN**

- [x] Pembayaran Operasional _(lihat di File **HASIL KETEMUAN KLIEN** yang kemarin sa kirim)_

- [x] Untuk yang Pembayaran Lainnya, jangan dulu

Endpoint ada di github, branch master

**Comment by imbrankarim** [comment]
> **OPERASIONAL SEWA ALAT DAN MOBIL**
> 
> * [ ]  OPERASIONAL SEWA ALAT dan MOBIL -> _cek apakah berfungsi kalau melapor tanggal yang sama muncul peringatan tidak boleh isi tanggal yang sama_

Sa coba insert ditanggal yg sama da lapor insert success kembaliannya dari server
